/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DeveloperRouteImport } from './routes/_developer'
import { Route as DoctorRouteImport } from './routes/_doctor'
import { Route as PatientRouteImport } from './routes/_patient'
import { Route as PosRouteImport } from './routes/_pos'
import { Route as ReceptionistRouteImport } from './routes/_receptionist'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardAddressesRouteImport } from './routes/_dashboard/addresses'
import { Route as DashboardAllergiesRouteImport } from './routes/_dashboard/allergies'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard/billing'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDiagnosesRouteImport } from './routes/_dashboard/diagnoses'
import { Route as DashboardDispensingRouteImport } from './routes/_dashboard/dispensing'
import { Route as DashboardDoctorsRouteImport } from './routes/_dashboard/doctors'
import { Route as DashboardMedicineCatalogRouteImport } from './routes/_dashboard/medicine-catalog'
import { Route as DashboardPatientsRouteImport } from './routes/_dashboard/patients'
import { Route as DashboardPrescriptionsRouteImport } from './routes/_dashboard/prescriptions'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardQueueRouteImport } from './routes/_dashboard/queue'
import { Route as DashboardShiftsRouteImport } from './routes/_dashboard/shifts'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/_dashboard/appointments/index'
import { Route as DashboardAppointmentsNewRouteImport } from './routes/_dashboard/appointments/new'
import { Route as DashboardOrganisationIndexRouteImport } from './routes/_dashboard/organisation/index'
import { Route as DashboardOrganisationDepartmentsRouteImport } from './routes/_dashboard/organisation/departments'
import { Route as DashboardOrganisationDesignationsRouteImport } from './routes/_dashboard/organisation/designations'
import { Route as DashboardOrganisationFinancialYearsRouteImport } from './routes/_dashboard/organisation/financial-years'
import { Route as DashboardOrganisationPrescriptionTemplatesRouteImport } from './routes/_dashboard/organisation/prescription-templates'
import { Route as DashboardOrganisationRolesRouteImport } from './routes/_dashboard/organisation/roles'
import { Route as DashboardOrganisationSidebarConfigRouteImport } from './routes/_dashboard/organisation/sidebar-config'
import { Route as DashboardOrganisationUsersRouteImport } from './routes/_dashboard/organisation/users'
import { Route as DashboardReportsDailyOpdSummaryRouteImport } from './routes/_dashboard/reports/daily-opd-summary'
import { Route as DashboardReportsDoctorWiseOpdRouteImport } from './routes/_dashboard/reports/doctor-wise-opd'
import { Route as DashboardReportsOutstandingPaymentsRouteImport } from './routes/_dashboard/reports/outstanding-payments'
import { Route as DashboardReportsRevenueCollectionRouteImport } from './routes/_dashboard/reports/revenue-collection'
import { Route as DeveloperDeveloperIndexRouteImport } from './routes/_developer/developer/index'
import { Route as DeveloperDeveloperApisRouteImport } from './routes/_developer/developer/apis'
import { Route as DeveloperDeveloperFeaturesRouteImport } from './routes/_developer/developer/features'
import { Route as DeveloperDeveloperModulesRouteImport } from './routes/_developer/developer/modules'
import { Route as DoctorDoctorIndexRouteImport } from './routes/_doctor/doctor/index'
import { Route as DoctorDoctorAdminRouteImport } from './routes/_doctor/doctor/admin'
import { Route as DoctorDoctorPrescriptionsRouteImport } from './routes/_doctor/doctor/prescriptions'
import { Route as DoctorDoctorProfileRouteImport } from './routes/_doctor/doctor/profile'
import { Route as PatientPatientIndexRouteImport } from './routes/_patient/patient/index'
import { Route as PatientPatientAppointmentsRouteImport } from './routes/_patient/patient/appointments'
import { Route as PatientPatientBillsRouteImport } from './routes/_patient/patient/bills'
import { Route as PatientPatientLabOrdersRouteImport } from './routes/_patient/patient/lab-orders'
import { Route as PatientPatientPrescriptionsRouteImport } from './routes/_patient/patient/prescriptions'
import { Route as PosPosIndexRouteImport } from './routes/_pos/pos/index'
import { Route as PosPosAppointmentsRouteImport } from './routes/_pos/pos/appointments'
import { Route as PosPosBillingRouteImport } from './routes/_pos/pos/billing'
import { Route as PosPosPatientsRouteImport } from './routes/_pos/pos/patients'
import { Route as ReceptionistReceptionistIndexRouteImport } from './routes/_receptionist/receptionist/index'
import { Route as ReceptionistReceptionistBillingRouteImport } from './routes/_receptionist/receptionist/billing'
import { Route as ReceptionistReceptionistDoctorsRouteImport } from './routes/_receptionist/receptionist/doctors'
import { Route as ReceptionistReceptionistPatientsRouteImport } from './routes/_receptionist/receptionist/patients'
import { Route as ReceptionistReceptionistPrescriptionsRouteImport } from './routes/_receptionist/receptionist/prescriptions'
import { Route as ReceptionistReceptionistProfileRouteImport } from './routes/_receptionist/receptionist/profile'
import { Route as DashboardAppointmentsAppointmentIdEditRouteImport } from './routes/_dashboard/appointments/$appointmentId.edit'
import { Route as DeveloperDeveloperSchemaIndexRouteImport } from './routes/_developer/developer/schema/index'
import { Route as DeveloperDeveloperSchemaModelRouteImport } from './routes/_developer/developer/schema/$model'
import { Route as DoctorDoctorAdminAppointmentsRouteImport } from './routes/_doctor/doctor/admin.appointments'
import { Route as DoctorDoctorAdminPrescriptionsRouteImport } from './routes/_doctor/doctor/admin.prescriptions'
import { Route as ReceptionistReceptionistAppointmentsIndexRouteImport } from './routes/_receptionist/receptionist/appointments/index'
import { Route as ReceptionistReceptionistAppointmentsNewRouteImport } from './routes/_receptionist/receptionist/appointments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/_developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/_patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/_pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/_receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAddressesRoute = DashboardAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAllergiesRoute = DashboardAllergiesRouteImport.update({
  id: '/allergies',
  path: '/allergies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiagnosesRoute = DashboardDiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDispensingRoute = DashboardDispensingRouteImport.update({
  id: '/dispensing',
  path: '/dispensing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicineCatalogRoute =
  DashboardMedicineCatalogRouteImport.update({
    id: '/medicine-catalog',
    path: '/medicine-catalog',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsRoute = DashboardPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShiftsRoute = DashboardShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsNewRoute =
  DashboardAppointmentsNewRouteImport.update({
    id: '/appointments/new',
    path: '/appointments/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationIndexRoute =
  DashboardOrganisationIndexRouteImport.update({
    id: '/organisation/',
    path: '/organisation/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationDepartmentsRoute =
  DashboardOrganisationDepartmentsRouteImport.update({
    id: '/organisation/departments',
    path: '/organisation/departments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationDesignationsRoute =
  DashboardOrganisationDesignationsRouteImport.update({
    id: '/organisation/designations',
    path: '/organisation/designations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationFinancialYearsRoute =
  DashboardOrganisationFinancialYearsRouteImport.update({
    id: '/organisation/financial-years',
    path: '/organisation/financial-years',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationPrescriptionTemplatesRoute =
  DashboardOrganisationPrescriptionTemplatesRouteImport.update({
    id: '/organisation/prescription-templates',
    path: '/organisation/prescription-templates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationRolesRoute =
  DashboardOrganisationRolesRouteImport.update({
    id: '/organisation/roles',
    path: '/organisation/roles',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationSidebarConfigRoute =
  DashboardOrganisationSidebarConfigRouteImport.update({
    id: '/organisation/sidebar-config',
    path: '/organisation/sidebar-config',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationUsersRoute =
  DashboardOrganisationUsersRouteImport.update({
    id: '/organisation/users',
    path: '/organisation/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsDailyOpdSummaryRoute =
  DashboardReportsDailyOpdSummaryRouteImport.update({
    id: '/reports/daily-opd-summary',
    path: '/reports/daily-opd-summary',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsDoctorWiseOpdRoute =
  DashboardReportsDoctorWiseOpdRouteImport.update({
    id: '/reports/doctor-wise-opd',
    path: '/reports/doctor-wise-opd',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsOutstandingPaymentsRoute =
  DashboardReportsOutstandingPaymentsRouteImport.update({
    id: '/reports/outstanding-payments',
    path: '/reports/outstanding-payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsRevenueCollectionRoute =
  DashboardReportsRevenueCollectionRouteImport.update({
    id: '/reports/revenue-collection',
    path: '/reports/revenue-collection',
    getParentRoute: () => DashboardRoute,
  } as any)
const DeveloperDeveloperIndexRoute = DeveloperDeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperDeveloperApisRoute = DeveloperDeveloperApisRouteImport.update({
  id: '/developer/apis',
  path: '/developer/apis',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperDeveloperFeaturesRoute =
  DeveloperDeveloperFeaturesRouteImport.update({
    id: '/developer/features',
    path: '/developer/features',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DeveloperDeveloperModulesRoute =
  DeveloperDeveloperModulesRouteImport.update({
    id: '/developer/modules',
    path: '/developer/modules',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DoctorDoctorIndexRoute = DoctorDoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDoctorAdminRoute = DoctorDoctorAdminRouteImport.update({
  id: '/doctor/admin',
  path: '/doctor/admin',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDoctorPrescriptionsRoute =
  DoctorDoctorPrescriptionsRouteImport.update({
    id: '/doctor/prescriptions',
    path: '/doctor/prescriptions',
    getParentRoute: () => DoctorRoute,
  } as any)
const DoctorDoctorProfileRoute = DoctorDoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientPatientIndexRoute = PatientPatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPatientAppointmentsRoute =
  PatientPatientAppointmentsRouteImport.update({
    id: '/patient/appointments',
    path: '/patient/appointments',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientPatientBillsRoute = PatientPatientBillsRouteImport.update({
  id: '/patient/bills',
  path: '/patient/bills',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPatientLabOrdersRoute = PatientPatientLabOrdersRouteImport.update({
  id: '/patient/lab-orders',
  path: '/patient/lab-orders',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPatientPrescriptionsRoute =
  PatientPatientPrescriptionsRouteImport.update({
    id: '/patient/prescriptions',
    path: '/patient/prescriptions',
    getParentRoute: () => PatientRoute,
  } as any)
const PosPosIndexRoute = PosPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => PosRoute,
} as any)
const PosPosAppointmentsRoute = PosPosAppointmentsRouteImport.update({
  id: '/pos/appointments',
  path: '/pos/appointments',
  getParentRoute: () => PosRoute,
} as any)
const PosPosBillingRoute = PosPosBillingRouteImport.update({
  id: '/pos/billing',
  path: '/pos/billing',
  getParentRoute: () => PosRoute,
} as any)
const PosPosPatientsRoute = PosPosPatientsRouteImport.update({
  id: '/pos/patients',
  path: '/pos/patients',
  getParentRoute: () => PosRoute,
} as any)
const ReceptionistReceptionistIndexRoute =
  ReceptionistReceptionistIndexRouteImport.update({
    id: '/receptionist/',
    path: '/receptionist/',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistReceptionistBillingRoute =
  ReceptionistReceptionistBillingRouteImport.update({
    id: '/receptionist/billing',
    path: '/receptionist/billing',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistReceptionistDoctorsRoute =
  ReceptionistReceptionistDoctorsRouteImport.update({
    id: '/receptionist/doctors',
    path: '/receptionist/doctors',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistReceptionistPatientsRoute =
  ReceptionistReceptionistPatientsRouteImport.update({
    id: '/receptionist/patients',
    path: '/receptionist/patients',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistReceptionistPrescriptionsRoute =
  ReceptionistReceptionistPrescriptionsRouteImport.update({
    id: '/receptionist/prescriptions',
    path: '/receptionist/prescriptions',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistReceptionistProfileRoute =
  ReceptionistReceptionistProfileRouteImport.update({
    id: '/receptionist/profile',
    path: '/receptionist/profile',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const DashboardAppointmentsAppointmentIdEditRoute =
  DashboardAppointmentsAppointmentIdEditRouteImport.update({
    id: '/appointments/$appointmentId/edit',
    path: '/appointments/$appointmentId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DeveloperDeveloperSchemaIndexRoute =
  DeveloperDeveloperSchemaIndexRouteImport.update({
    id: '/developer/schema/',
    path: '/developer/schema/',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DeveloperDeveloperSchemaModelRoute =
  DeveloperDeveloperSchemaModelRouteImport.update({
    id: '/developer/schema/$model',
    path: '/developer/schema/$model',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DoctorDoctorAdminAppointmentsRoute =
  DoctorDoctorAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DoctorDoctorAdminRoute,
  } as any)
const DoctorDoctorAdminPrescriptionsRoute =
  DoctorDoctorAdminPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => DoctorDoctorAdminRoute,
  } as any)
const ReceptionistReceptionistAppointmentsIndexRoute =
  ReceptionistReceptionistAppointmentsIndexRouteImport.update({
    id: '/receptionist/appointments/',
    path: '/receptionist/appointments/',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistReceptionistAppointmentsNewRoute =
  ReceptionistReceptionistAppointmentsNewRouteImport.update({
    id: '/receptionist/appointments/new',
    path: '/receptionist/appointments/new',
    getParentRoute: () => ReceptionistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/addresses': typeof DashboardAddressesRoute
  '/allergies': typeof DashboardAllergiesRoute
  '/billing': typeof DashboardBillingRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/diagnoses': typeof DashboardDiagnosesRoute
  '/dispensing': typeof DashboardDispensingRoute
  '/doctors': typeof DashboardDoctorsRoute
  '/medicine-catalog': typeof DashboardMedicineCatalogRoute
  '/patients': typeof DashboardPatientsRoute
  '/prescriptions': typeof DashboardPrescriptionsRoute
  '/profile': typeof DashboardProfileRoute
  '/queue': typeof DashboardQueueRoute
  '/shifts': typeof DashboardShiftsRoute
  '/appointments/new': typeof DashboardAppointmentsNewRoute
  '/organisation/departments': typeof DashboardOrganisationDepartmentsRoute
  '/organisation/designations': typeof DashboardOrganisationDesignationsRoute
  '/organisation/financial-years': typeof DashboardOrganisationFinancialYearsRoute
  '/organisation/prescription-templates': typeof DashboardOrganisationPrescriptionTemplatesRoute
  '/organisation/roles': typeof DashboardOrganisationRolesRoute
  '/organisation/sidebar-config': typeof DashboardOrganisationSidebarConfigRoute
  '/organisation/users': typeof DashboardOrganisationUsersRoute
  '/reports/daily-opd-summary': typeof DashboardReportsDailyOpdSummaryRoute
  '/reports/doctor-wise-opd': typeof DashboardReportsDoctorWiseOpdRoute
  '/reports/outstanding-payments': typeof DashboardReportsOutstandingPaymentsRoute
  '/reports/revenue-collection': typeof DashboardReportsRevenueCollectionRoute
  '/developer/apis': typeof DeveloperDeveloperApisRoute
  '/developer/features': typeof DeveloperDeveloperFeaturesRoute
  '/developer/modules': typeof DeveloperDeveloperModulesRoute
  '/doctor/admin': typeof DoctorDoctorAdminRouteWithChildren
  '/doctor/prescriptions': typeof DoctorDoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorDoctorProfileRoute
  '/patient/appointments': typeof PatientPatientAppointmentsRoute
  '/patient/bills': typeof PatientPatientBillsRoute
  '/patient/lab-orders': typeof PatientPatientLabOrdersRoute
  '/patient/prescriptions': typeof PatientPatientPrescriptionsRoute
  '/pos/appointments': typeof PosPosAppointmentsRoute
  '/pos/billing': typeof PosPosBillingRoute
  '/pos/patients': typeof PosPosPatientsRoute
  '/receptionist/billing': typeof ReceptionistReceptionistBillingRoute
  '/receptionist/doctors': typeof ReceptionistReceptionistDoctorsRoute
  '/receptionist/patients': typeof ReceptionistReceptionistPatientsRoute
  '/receptionist/prescriptions': typeof ReceptionistReceptionistPrescriptionsRoute
  '/receptionist/profile': typeof ReceptionistReceptionistProfileRoute
  '/appointments/': typeof DashboardAppointmentsIndexRoute
  '/organisation/': typeof DashboardOrganisationIndexRoute
  '/developer/': typeof DeveloperDeveloperIndexRoute
  '/doctor/': typeof DoctorDoctorIndexRoute
  '/patient/': typeof PatientPatientIndexRoute
  '/pos/': typeof PosPosIndexRoute
  '/receptionist/': typeof ReceptionistReceptionistIndexRoute
  '/appointments/$appointmentId/edit': typeof DashboardAppointmentsAppointmentIdEditRoute
  '/developer/schema/$model': typeof DeveloperDeveloperSchemaModelRoute
  '/doctor/admin/appointments': typeof DoctorDoctorAdminAppointmentsRoute
  '/doctor/admin/prescriptions': typeof DoctorDoctorAdminPrescriptionsRoute
  '/receptionist/appointments/new': typeof ReceptionistReceptionistAppointmentsNewRoute
  '/developer/schema/': typeof DeveloperDeveloperSchemaIndexRoute
  '/receptionist/appointments/': typeof ReceptionistReceptionistAppointmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/addresses': typeof DashboardAddressesRoute
  '/allergies': typeof DashboardAllergiesRoute
  '/billing': typeof DashboardBillingRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/diagnoses': typeof DashboardDiagnosesRoute
  '/dispensing': typeof DashboardDispensingRoute
  '/doctors': typeof DashboardDoctorsRoute
  '/medicine-catalog': typeof DashboardMedicineCatalogRoute
  '/patients': typeof DashboardPatientsRoute
  '/prescriptions': typeof DashboardPrescriptionsRoute
  '/profile': typeof DashboardProfileRoute
  '/queue': typeof DashboardQueueRoute
  '/shifts': typeof DashboardShiftsRoute
  '/appointments/new': typeof DashboardAppointmentsNewRoute
  '/organisation/departments': typeof DashboardOrganisationDepartmentsRoute
  '/organisation/designations': typeof DashboardOrganisationDesignationsRoute
  '/organisation/financial-years': typeof DashboardOrganisationFinancialYearsRoute
  '/organisation/prescription-templates': typeof DashboardOrganisationPrescriptionTemplatesRoute
  '/organisation/roles': typeof DashboardOrganisationRolesRoute
  '/organisation/sidebar-config': typeof DashboardOrganisationSidebarConfigRoute
  '/organisation/users': typeof DashboardOrganisationUsersRoute
  '/reports/daily-opd-summary': typeof DashboardReportsDailyOpdSummaryRoute
  '/reports/doctor-wise-opd': typeof DashboardReportsDoctorWiseOpdRoute
  '/reports/outstanding-payments': typeof DashboardReportsOutstandingPaymentsRoute
  '/reports/revenue-collection': typeof DashboardReportsRevenueCollectionRoute
  '/developer/apis': typeof DeveloperDeveloperApisRoute
  '/developer/features': typeof DeveloperDeveloperFeaturesRoute
  '/developer/modules': typeof DeveloperDeveloperModulesRoute
  '/doctor/admin': typeof DoctorDoctorAdminRouteWithChildren
  '/doctor/prescriptions': typeof DoctorDoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorDoctorProfileRoute
  '/patient/appointments': typeof PatientPatientAppointmentsRoute
  '/patient/bills': typeof PatientPatientBillsRoute
  '/patient/lab-orders': typeof PatientPatientLabOrdersRoute
  '/patient/prescriptions': typeof PatientPatientPrescriptionsRoute
  '/pos/appointments': typeof PosPosAppointmentsRoute
  '/pos/billing': typeof PosPosBillingRoute
  '/pos/patients': typeof PosPosPatientsRoute
  '/receptionist/billing': typeof ReceptionistReceptionistBillingRoute
  '/receptionist/doctors': typeof ReceptionistReceptionistDoctorsRoute
  '/receptionist/patients': typeof ReceptionistReceptionistPatientsRoute
  '/receptionist/prescriptions': typeof ReceptionistReceptionistPrescriptionsRoute
  '/receptionist/profile': typeof ReceptionistReceptionistProfileRoute
  '/appointments': typeof DashboardAppointmentsIndexRoute
  '/organisation': typeof DashboardOrganisationIndexRoute
  '/developer': typeof DeveloperDeveloperIndexRoute
  '/doctor': typeof DoctorDoctorIndexRoute
  '/patient': typeof PatientPatientIndexRoute
  '/pos': typeof PosPosIndexRoute
  '/receptionist': typeof ReceptionistReceptionistIndexRoute
  '/appointments/$appointmentId/edit': typeof DashboardAppointmentsAppointmentIdEditRoute
  '/developer/schema/$model': typeof DeveloperDeveloperSchemaModelRoute
  '/doctor/admin/appointments': typeof DoctorDoctorAdminAppointmentsRoute
  '/doctor/admin/prescriptions': typeof DoctorDoctorAdminPrescriptionsRoute
  '/receptionist/appointments/new': typeof ReceptionistReceptionistAppointmentsNewRoute
  '/developer/schema': typeof DeveloperDeveloperSchemaIndexRoute
  '/receptionist/appointments': typeof ReceptionistReceptionistAppointmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_developer': typeof DeveloperRouteWithChildren
  '/_doctor': typeof DoctorRouteWithChildren
  '/_patient': typeof PatientRouteWithChildren
  '/_pos': typeof PosRouteWithChildren
  '/_receptionist': typeof ReceptionistRouteWithChildren
  '/display': typeof DisplayRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/_dashboard/addresses': typeof DashboardAddressesRoute
  '/_dashboard/allergies': typeof DashboardAllergiesRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/diagnoses': typeof DashboardDiagnosesRoute
  '/_dashboard/dispensing': typeof DashboardDispensingRoute
  '/_dashboard/doctors': typeof DashboardDoctorsRoute
  '/_dashboard/medicine-catalog': typeof DashboardMedicineCatalogRoute
  '/_dashboard/patients': typeof DashboardPatientsRoute
  '/_dashboard/prescriptions': typeof DashboardPrescriptionsRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/queue': typeof DashboardQueueRoute
  '/_dashboard/shifts': typeof DashboardShiftsRoute
  '/_dashboard/appointments/new': typeof DashboardAppointmentsNewRoute
  '/_dashboard/organisation/departments': typeof DashboardOrganisationDepartmentsRoute
  '/_dashboard/organisation/designations': typeof DashboardOrganisationDesignationsRoute
  '/_dashboard/organisation/financial-years': typeof DashboardOrganisationFinancialYearsRoute
  '/_dashboard/organisation/prescription-templates': typeof DashboardOrganisationPrescriptionTemplatesRoute
  '/_dashboard/organisation/roles': typeof DashboardOrganisationRolesRoute
  '/_dashboard/organisation/sidebar-config': typeof DashboardOrganisationSidebarConfigRoute
  '/_dashboard/organisation/users': typeof DashboardOrganisationUsersRoute
  '/_dashboard/reports/daily-opd-summary': typeof DashboardReportsDailyOpdSummaryRoute
  '/_dashboard/reports/doctor-wise-opd': typeof DashboardReportsDoctorWiseOpdRoute
  '/_dashboard/reports/outstanding-payments': typeof DashboardReportsOutstandingPaymentsRoute
  '/_dashboard/reports/revenue-collection': typeof DashboardReportsRevenueCollectionRoute
  '/_developer/developer/apis': typeof DeveloperDeveloperApisRoute
  '/_developer/developer/features': typeof DeveloperDeveloperFeaturesRoute
  '/_developer/developer/modules': typeof DeveloperDeveloperModulesRoute
  '/_doctor/doctor/admin': typeof DoctorDoctorAdminRouteWithChildren
  '/_doctor/doctor/prescriptions': typeof DoctorDoctorPrescriptionsRoute
  '/_doctor/doctor/profile': typeof DoctorDoctorProfileRoute
  '/_patient/patient/appointments': typeof PatientPatientAppointmentsRoute
  '/_patient/patient/bills': typeof PatientPatientBillsRoute
  '/_patient/patient/lab-orders': typeof PatientPatientLabOrdersRoute
  '/_patient/patient/prescriptions': typeof PatientPatientPrescriptionsRoute
  '/_pos/pos/appointments': typeof PosPosAppointmentsRoute
  '/_pos/pos/billing': typeof PosPosBillingRoute
  '/_pos/pos/patients': typeof PosPosPatientsRoute
  '/_receptionist/receptionist/billing': typeof ReceptionistReceptionistBillingRoute
  '/_receptionist/receptionist/doctors': typeof ReceptionistReceptionistDoctorsRoute
  '/_receptionist/receptionist/patients': typeof ReceptionistReceptionistPatientsRoute
  '/_receptionist/receptionist/prescriptions': typeof ReceptionistReceptionistPrescriptionsRoute
  '/_receptionist/receptionist/profile': typeof ReceptionistReceptionistProfileRoute
  '/_dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/_dashboard/organisation/': typeof DashboardOrganisationIndexRoute
  '/_developer/developer/': typeof DeveloperDeveloperIndexRoute
  '/_doctor/doctor/': typeof DoctorDoctorIndexRoute
  '/_patient/patient/': typeof PatientPatientIndexRoute
  '/_pos/pos/': typeof PosPosIndexRoute
  '/_receptionist/receptionist/': typeof ReceptionistReceptionistIndexRoute
  '/_dashboard/appointments/$appointmentId/edit': typeof DashboardAppointmentsAppointmentIdEditRoute
  '/_developer/developer/schema/$model': typeof DeveloperDeveloperSchemaModelRoute
  '/_doctor/doctor/admin/appointments': typeof DoctorDoctorAdminAppointmentsRoute
  '/_doctor/doctor/admin/prescriptions': typeof DoctorDoctorAdminPrescriptionsRoute
  '/_receptionist/receptionist/appointments/new': typeof ReceptionistReceptionistAppointmentsNewRoute
  '/_developer/developer/schema/': typeof DeveloperDeveloperSchemaIndexRoute
  '/_receptionist/receptionist/appointments/': typeof ReceptionistReceptionistAppointmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/display'
    | '/help'
    | '/login'
    | '/addresses'
    | '/allergies'
    | '/billing'
    | '/dashboard'
    | '/diagnoses'
    | '/dispensing'
    | '/doctors'
    | '/medicine-catalog'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/queue'
    | '/shifts'
    | '/appointments/new'
    | '/organisation/departments'
    | '/organisation/designations'
    | '/organisation/financial-years'
    | '/organisation/prescription-templates'
    | '/organisation/roles'
    | '/organisation/sidebar-config'
    | '/organisation/users'
    | '/reports/daily-opd-summary'
    | '/reports/doctor-wise-opd'
    | '/reports/outstanding-payments'
    | '/reports/revenue-collection'
    | '/developer/apis'
    | '/developer/features'
    | '/developer/modules'
    | '/doctor/admin'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/lab-orders'
    | '/patient/prescriptions'
    | '/pos/appointments'
    | '/pos/billing'
    | '/pos/patients'
    | '/receptionist/billing'
    | '/receptionist/doctors'
    | '/receptionist/patients'
    | '/receptionist/prescriptions'
    | '/receptionist/profile'
    | '/appointments/'
    | '/organisation/'
    | '/developer/'
    | '/doctor/'
    | '/patient/'
    | '/pos/'
    | '/receptionist/'
    | '/appointments/$appointmentId/edit'
    | '/developer/schema/$model'
    | '/doctor/admin/appointments'
    | '/doctor/admin/prescriptions'
    | '/receptionist/appointments/new'
    | '/developer/schema/'
    | '/receptionist/appointments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/display'
    | '/help'
    | '/login'
    | '/addresses'
    | '/allergies'
    | '/billing'
    | '/dashboard'
    | '/diagnoses'
    | '/dispensing'
    | '/doctors'
    | '/medicine-catalog'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/queue'
    | '/shifts'
    | '/appointments/new'
    | '/organisation/departments'
    | '/organisation/designations'
    | '/organisation/financial-years'
    | '/organisation/prescription-templates'
    | '/organisation/roles'
    | '/organisation/sidebar-config'
    | '/organisation/users'
    | '/reports/daily-opd-summary'
    | '/reports/doctor-wise-opd'
    | '/reports/outstanding-payments'
    | '/reports/revenue-collection'
    | '/developer/apis'
    | '/developer/features'
    | '/developer/modules'
    | '/doctor/admin'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/lab-orders'
    | '/patient/prescriptions'
    | '/pos/appointments'
    | '/pos/billing'
    | '/pos/patients'
    | '/receptionist/billing'
    | '/receptionist/doctors'
    | '/receptionist/patients'
    | '/receptionist/prescriptions'
    | '/receptionist/profile'
    | '/appointments'
    | '/organisation'
    | '/developer'
    | '/doctor'
    | '/patient'
    | '/pos'
    | '/receptionist'
    | '/appointments/$appointmentId/edit'
    | '/developer/schema/$model'
    | '/doctor/admin/appointments'
    | '/doctor/admin/prescriptions'
    | '/receptionist/appointments/new'
    | '/developer/schema'
    | '/receptionist/appointments'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_developer'
    | '/_doctor'
    | '/_patient'
    | '/_pos'
    | '/_receptionist'
    | '/display'
    | '/help'
    | '/login'
    | '/_dashboard/addresses'
    | '/_dashboard/allergies'
    | '/_dashboard/billing'
    | '/_dashboard/dashboard'
    | '/_dashboard/diagnoses'
    | '/_dashboard/dispensing'
    | '/_dashboard/doctors'
    | '/_dashboard/medicine-catalog'
    | '/_dashboard/patients'
    | '/_dashboard/prescriptions'
    | '/_dashboard/profile'
    | '/_dashboard/queue'
    | '/_dashboard/shifts'
    | '/_dashboard/appointments/new'
    | '/_dashboard/organisation/departments'
    | '/_dashboard/organisation/designations'
    | '/_dashboard/organisation/financial-years'
    | '/_dashboard/organisation/prescription-templates'
    | '/_dashboard/organisation/roles'
    | '/_dashboard/organisation/sidebar-config'
    | '/_dashboard/organisation/users'
    | '/_dashboard/reports/daily-opd-summary'
    | '/_dashboard/reports/doctor-wise-opd'
    | '/_dashboard/reports/outstanding-payments'
    | '/_dashboard/reports/revenue-collection'
    | '/_developer/developer/apis'
    | '/_developer/developer/features'
    | '/_developer/developer/modules'
    | '/_doctor/doctor/admin'
    | '/_doctor/doctor/prescriptions'
    | '/_doctor/doctor/profile'
    | '/_patient/patient/appointments'
    | '/_patient/patient/bills'
    | '/_patient/patient/lab-orders'
    | '/_patient/patient/prescriptions'
    | '/_pos/pos/appointments'
    | '/_pos/pos/billing'
    | '/_pos/pos/patients'
    | '/_receptionist/receptionist/billing'
    | '/_receptionist/receptionist/doctors'
    | '/_receptionist/receptionist/patients'
    | '/_receptionist/receptionist/prescriptions'
    | '/_receptionist/receptionist/profile'
    | '/_dashboard/appointments/'
    | '/_dashboard/organisation/'
    | '/_developer/developer/'
    | '/_doctor/doctor/'
    | '/_patient/patient/'
    | '/_pos/pos/'
    | '/_receptionist/receptionist/'
    | '/_dashboard/appointments/$appointmentId/edit'
    | '/_developer/developer/schema/$model'
    | '/_doctor/doctor/admin/appointments'
    | '/_doctor/doctor/admin/prescriptions'
    | '/_receptionist/receptionist/appointments/new'
    | '/_developer/developer/schema/'
    | '/_receptionist/receptionist/appointments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeveloperRoute: typeof DeveloperRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  PosRoute: typeof PosRouteWithChildren
  ReceptionistRoute: typeof ReceptionistRouteWithChildren
  DisplayRoute: typeof DisplayRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developer': {
      id: '/_developer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_patient': {
      id: '/_patient'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos': {
      id: '/_pos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_receptionist': {
      id: '/_receptionist'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/addresses': {
      id: '/_dashboard/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof DashboardAddressesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/allergies': {
      id: '/_dashboard/allergies'
      path: '/allergies'
      fullPath: '/allergies'
      preLoaderRoute: typeof DashboardAllergiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/diagnoses': {
      id: '/_dashboard/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof DashboardDiagnosesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dispensing': {
      id: '/_dashboard/dispensing'
      path: '/dispensing'
      fullPath: '/dispensing'
      preLoaderRoute: typeof DashboardDispensingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/doctors': {
      id: '/_dashboard/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/medicine-catalog': {
      id: '/_dashboard/medicine-catalog'
      path: '/medicine-catalog'
      fullPath: '/medicine-catalog'
      preLoaderRoute: typeof DashboardMedicineCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/patients': {
      id: '/_dashboard/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/prescriptions': {
      id: '/_dashboard/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/queue': {
      id: '/_dashboard/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shifts': {
      id: '/_dashboard/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof DashboardShiftsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments/': {
      id: '/_dashboard/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments/new': {
      id: '/_dashboard/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof DashboardAppointmentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/': {
      id: '/_dashboard/organisation/'
      path: '/organisation'
      fullPath: '/organisation/'
      preLoaderRoute: typeof DashboardOrganisationIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/departments': {
      id: '/_dashboard/organisation/departments'
      path: '/organisation/departments'
      fullPath: '/organisation/departments'
      preLoaderRoute: typeof DashboardOrganisationDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/designations': {
      id: '/_dashboard/organisation/designations'
      path: '/organisation/designations'
      fullPath: '/organisation/designations'
      preLoaderRoute: typeof DashboardOrganisationDesignationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/financial-years': {
      id: '/_dashboard/organisation/financial-years'
      path: '/organisation/financial-years'
      fullPath: '/organisation/financial-years'
      preLoaderRoute: typeof DashboardOrganisationFinancialYearsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/prescription-templates': {
      id: '/_dashboard/organisation/prescription-templates'
      path: '/organisation/prescription-templates'
      fullPath: '/organisation/prescription-templates'
      preLoaderRoute: typeof DashboardOrganisationPrescriptionTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/roles': {
      id: '/_dashboard/organisation/roles'
      path: '/organisation/roles'
      fullPath: '/organisation/roles'
      preLoaderRoute: typeof DashboardOrganisationRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/sidebar-config': {
      id: '/_dashboard/organisation/sidebar-config'
      path: '/organisation/sidebar-config'
      fullPath: '/organisation/sidebar-config'
      preLoaderRoute: typeof DashboardOrganisationSidebarConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/users': {
      id: '/_dashboard/organisation/users'
      path: '/organisation/users'
      fullPath: '/organisation/users'
      preLoaderRoute: typeof DashboardOrganisationUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/daily-opd-summary': {
      id: '/_dashboard/reports/daily-opd-summary'
      path: '/reports/daily-opd-summary'
      fullPath: '/reports/daily-opd-summary'
      preLoaderRoute: typeof DashboardReportsDailyOpdSummaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/doctor-wise-opd': {
      id: '/_dashboard/reports/doctor-wise-opd'
      path: '/reports/doctor-wise-opd'
      fullPath: '/reports/doctor-wise-opd'
      preLoaderRoute: typeof DashboardReportsDoctorWiseOpdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/outstanding-payments': {
      id: '/_dashboard/reports/outstanding-payments'
      path: '/reports/outstanding-payments'
      fullPath: '/reports/outstanding-payments'
      preLoaderRoute: typeof DashboardReportsOutstandingPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/revenue-collection': {
      id: '/_dashboard/reports/revenue-collection'
      path: '/reports/revenue-collection'
      fullPath: '/reports/revenue-collection'
      preLoaderRoute: typeof DashboardReportsRevenueCollectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_developer/developer/': {
      id: '/_developer/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperDeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/_developer/developer/apis': {
      id: '/_developer/developer/apis'
      path: '/developer/apis'
      fullPath: '/developer/apis'
      preLoaderRoute: typeof DeveloperDeveloperApisRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/_developer/developer/features': {
      id: '/_developer/developer/features'
      path: '/developer/features'
      fullPath: '/developer/features'
      preLoaderRoute: typeof DeveloperDeveloperFeaturesRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/_developer/developer/modules': {
      id: '/_developer/developer/modules'
      path: '/developer/modules'
      fullPath: '/developer/modules'
      preLoaderRoute: typeof DeveloperDeveloperModulesRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/_doctor/doctor/': {
      id: '/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorDoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/_doctor/doctor/admin': {
      id: '/_doctor/doctor/admin'
      path: '/doctor/admin'
      fullPath: '/doctor/admin'
      preLoaderRoute: typeof DoctorDoctorAdminRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/_doctor/doctor/prescriptions': {
      id: '/_doctor/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorDoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/_doctor/doctor/profile': {
      id: '/_doctor/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorDoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/_patient/patient/': {
      id: '/_patient/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientPatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/patient/appointments': {
      id: '/_patient/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientPatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/patient/bills': {
      id: '/_patient/patient/bills'
      path: '/patient/bills'
      fullPath: '/patient/bills'
      preLoaderRoute: typeof PatientPatientBillsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/patient/lab-orders': {
      id: '/_patient/patient/lab-orders'
      path: '/patient/lab-orders'
      fullPath: '/patient/lab-orders'
      preLoaderRoute: typeof PatientPatientLabOrdersRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/patient/prescriptions': {
      id: '/_patient/patient/prescriptions'
      path: '/patient/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_pos/pos/': {
      id: '/_pos/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosPosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/pos/appointments': {
      id: '/_pos/pos/appointments'
      path: '/pos/appointments'
      fullPath: '/pos/appointments'
      preLoaderRoute: typeof PosPosAppointmentsRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/pos/billing': {
      id: '/_pos/pos/billing'
      path: '/pos/billing'
      fullPath: '/pos/billing'
      preLoaderRoute: typeof PosPosBillingRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/pos/patients': {
      id: '/_pos/pos/patients'
      path: '/pos/patients'
      fullPath: '/pos/patients'
      preLoaderRoute: typeof PosPosPatientsRouteImport
      parentRoute: typeof PosRoute
    }
    '/_receptionist/receptionist/': {
      id: '/_receptionist/receptionist/'
      path: '/receptionist'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof ReceptionistReceptionistIndexRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_receptionist/receptionist/billing': {
      id: '/_receptionist/receptionist/billing'
      path: '/receptionist/billing'
      fullPath: '/receptionist/billing'
      preLoaderRoute: typeof ReceptionistReceptionistBillingRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_receptionist/receptionist/doctors': {
      id: '/_receptionist/receptionist/doctors'
      path: '/receptionist/doctors'
      fullPath: '/receptionist/doctors'
      preLoaderRoute: typeof ReceptionistReceptionistDoctorsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_receptionist/receptionist/patients': {
      id: '/_receptionist/receptionist/patients'
      path: '/receptionist/patients'
      fullPath: '/receptionist/patients'
      preLoaderRoute: typeof ReceptionistReceptionistPatientsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_receptionist/receptionist/prescriptions': {
      id: '/_receptionist/receptionist/prescriptions'
      path: '/receptionist/prescriptions'
      fullPath: '/receptionist/prescriptions'
      preLoaderRoute: typeof ReceptionistReceptionistPrescriptionsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_receptionist/receptionist/profile': {
      id: '/_receptionist/receptionist/profile'
      path: '/receptionist/profile'
      fullPath: '/receptionist/profile'
      preLoaderRoute: typeof ReceptionistReceptionistProfileRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_dashboard/appointments/$appointmentId/edit': {
      id: '/_dashboard/appointments/$appointmentId/edit'
      path: '/appointments/$appointmentId/edit'
      fullPath: '/appointments/$appointmentId/edit'
      preLoaderRoute: typeof DashboardAppointmentsAppointmentIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_developer/developer/schema/': {
      id: '/_developer/developer/schema/'
      path: '/developer/schema'
      fullPath: '/developer/schema/'
      preLoaderRoute: typeof DeveloperDeveloperSchemaIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/_developer/developer/schema/$model': {
      id: '/_developer/developer/schema/$model'
      path: '/developer/schema/$model'
      fullPath: '/developer/schema/$model'
      preLoaderRoute: typeof DeveloperDeveloperSchemaModelRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/_doctor/doctor/admin/appointments': {
      id: '/_doctor/doctor/admin/appointments'
      path: '/appointments'
      fullPath: '/doctor/admin/appointments'
      preLoaderRoute: typeof DoctorDoctorAdminAppointmentsRouteImport
      parentRoute: typeof DoctorDoctorAdminRoute
    }
    '/_doctor/doctor/admin/prescriptions': {
      id: '/_doctor/doctor/admin/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/admin/prescriptions'
      preLoaderRoute: typeof DoctorDoctorAdminPrescriptionsRouteImport
      parentRoute: typeof DoctorDoctorAdminRoute
    }
    '/_receptionist/receptionist/appointments/': {
      id: '/_receptionist/receptionist/appointments/'
      path: '/receptionist/appointments'
      fullPath: '/receptionist/appointments/'
      preLoaderRoute: typeof ReceptionistReceptionistAppointmentsIndexRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/_receptionist/receptionist/appointments/new': {
      id: '/_receptionist/receptionist/appointments/new'
      path: '/receptionist/appointments/new'
      fullPath: '/receptionist/appointments/new'
      preLoaderRoute: typeof ReceptionistReceptionistAppointmentsNewRouteImport
      parentRoute: typeof ReceptionistRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddressesRoute: typeof DashboardAddressesRoute
  DashboardAllergiesRoute: typeof DashboardAllergiesRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDiagnosesRoute: typeof DashboardDiagnosesRoute
  DashboardDispensingRoute: typeof DashboardDispensingRoute
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardMedicineCatalogRoute: typeof DashboardMedicineCatalogRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardPrescriptionsRoute: typeof DashboardPrescriptionsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardShiftsRoute: typeof DashboardShiftsRoute
  DashboardAppointmentsNewRoute: typeof DashboardAppointmentsNewRoute
  DashboardOrganisationDepartmentsRoute: typeof DashboardOrganisationDepartmentsRoute
  DashboardOrganisationDesignationsRoute: typeof DashboardOrganisationDesignationsRoute
  DashboardOrganisationFinancialYearsRoute: typeof DashboardOrganisationFinancialYearsRoute
  DashboardOrganisationPrescriptionTemplatesRoute: typeof DashboardOrganisationPrescriptionTemplatesRoute
  DashboardOrganisationRolesRoute: typeof DashboardOrganisationRolesRoute
  DashboardOrganisationSidebarConfigRoute: typeof DashboardOrganisationSidebarConfigRoute
  DashboardOrganisationUsersRoute: typeof DashboardOrganisationUsersRoute
  DashboardReportsDailyOpdSummaryRoute: typeof DashboardReportsDailyOpdSummaryRoute
  DashboardReportsDoctorWiseOpdRoute: typeof DashboardReportsDoctorWiseOpdRoute
  DashboardReportsOutstandingPaymentsRoute: typeof DashboardReportsOutstandingPaymentsRoute
  DashboardReportsRevenueCollectionRoute: typeof DashboardReportsRevenueCollectionRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardOrganisationIndexRoute: typeof DashboardOrganisationIndexRoute
  DashboardAppointmentsAppointmentIdEditRoute: typeof DashboardAppointmentsAppointmentIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddressesRoute: DashboardAddressesRoute,
  DashboardAllergiesRoute: DashboardAllergiesRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDiagnosesRoute: DashboardDiagnosesRoute,
  DashboardDispensingRoute: DashboardDispensingRoute,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardMedicineCatalogRoute: DashboardMedicineCatalogRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardPrescriptionsRoute: DashboardPrescriptionsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardShiftsRoute: DashboardShiftsRoute,
  DashboardAppointmentsNewRoute: DashboardAppointmentsNewRoute,
  DashboardOrganisationDepartmentsRoute: DashboardOrganisationDepartmentsRoute,
  DashboardOrganisationDesignationsRoute:
    DashboardOrganisationDesignationsRoute,
  DashboardOrganisationFinancialYearsRoute:
    DashboardOrganisationFinancialYearsRoute,
  DashboardOrganisationPrescriptionTemplatesRoute:
    DashboardOrganisationPrescriptionTemplatesRoute,
  DashboardOrganisationRolesRoute: DashboardOrganisationRolesRoute,
  DashboardOrganisationSidebarConfigRoute:
    DashboardOrganisationSidebarConfigRoute,
  DashboardOrganisationUsersRoute: DashboardOrganisationUsersRoute,
  DashboardReportsDailyOpdSummaryRoute: DashboardReportsDailyOpdSummaryRoute,
  DashboardReportsDoctorWiseOpdRoute: DashboardReportsDoctorWiseOpdRoute,
  DashboardReportsOutstandingPaymentsRoute:
    DashboardReportsOutstandingPaymentsRoute,
  DashboardReportsRevenueCollectionRoute:
    DashboardReportsRevenueCollectionRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardOrganisationIndexRoute: DashboardOrganisationIndexRoute,
  DashboardAppointmentsAppointmentIdEditRoute:
    DashboardAppointmentsAppointmentIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeveloperRouteChildren {
  DeveloperDeveloperApisRoute: typeof DeveloperDeveloperApisRoute
  DeveloperDeveloperFeaturesRoute: typeof DeveloperDeveloperFeaturesRoute
  DeveloperDeveloperModulesRoute: typeof DeveloperDeveloperModulesRoute
  DeveloperDeveloperIndexRoute: typeof DeveloperDeveloperIndexRoute
  DeveloperDeveloperSchemaModelRoute: typeof DeveloperDeveloperSchemaModelRoute
  DeveloperDeveloperSchemaIndexRoute: typeof DeveloperDeveloperSchemaIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperDeveloperApisRoute: DeveloperDeveloperApisRoute,
  DeveloperDeveloperFeaturesRoute: DeveloperDeveloperFeaturesRoute,
  DeveloperDeveloperModulesRoute: DeveloperDeveloperModulesRoute,
  DeveloperDeveloperIndexRoute: DeveloperDeveloperIndexRoute,
  DeveloperDeveloperSchemaModelRoute: DeveloperDeveloperSchemaModelRoute,
  DeveloperDeveloperSchemaIndexRoute: DeveloperDeveloperSchemaIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface DoctorDoctorAdminRouteChildren {
  DoctorDoctorAdminAppointmentsRoute: typeof DoctorDoctorAdminAppointmentsRoute
  DoctorDoctorAdminPrescriptionsRoute: typeof DoctorDoctorAdminPrescriptionsRoute
}

const DoctorDoctorAdminRouteChildren: DoctorDoctorAdminRouteChildren = {
  DoctorDoctorAdminAppointmentsRoute: DoctorDoctorAdminAppointmentsRoute,
  DoctorDoctorAdminPrescriptionsRoute: DoctorDoctorAdminPrescriptionsRoute,
}

const DoctorDoctorAdminRouteWithChildren =
  DoctorDoctorAdminRoute._addFileChildren(DoctorDoctorAdminRouteChildren)

interface DoctorRouteChildren {
  DoctorDoctorAdminRoute: typeof DoctorDoctorAdminRouteWithChildren
  DoctorDoctorPrescriptionsRoute: typeof DoctorDoctorPrescriptionsRoute
  DoctorDoctorProfileRoute: typeof DoctorDoctorProfileRoute
  DoctorDoctorIndexRoute: typeof DoctorDoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorDoctorAdminRoute: DoctorDoctorAdminRouteWithChildren,
  DoctorDoctorPrescriptionsRoute: DoctorDoctorPrescriptionsRoute,
  DoctorDoctorProfileRoute: DoctorDoctorProfileRoute,
  DoctorDoctorIndexRoute: DoctorDoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientPatientAppointmentsRoute: typeof PatientPatientAppointmentsRoute
  PatientPatientBillsRoute: typeof PatientPatientBillsRoute
  PatientPatientLabOrdersRoute: typeof PatientPatientLabOrdersRoute
  PatientPatientPrescriptionsRoute: typeof PatientPatientPrescriptionsRoute
  PatientPatientIndexRoute: typeof PatientPatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientPatientAppointmentsRoute: PatientPatientAppointmentsRoute,
  PatientPatientBillsRoute: PatientPatientBillsRoute,
  PatientPatientLabOrdersRoute: PatientPatientLabOrdersRoute,
  PatientPatientPrescriptionsRoute: PatientPatientPrescriptionsRoute,
  PatientPatientIndexRoute: PatientPatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PosRouteChildren {
  PosPosAppointmentsRoute: typeof PosPosAppointmentsRoute
  PosPosBillingRoute: typeof PosPosBillingRoute
  PosPosPatientsRoute: typeof PosPosPatientsRoute
  PosPosIndexRoute: typeof PosPosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosPosAppointmentsRoute: PosPosAppointmentsRoute,
  PosPosBillingRoute: PosPosBillingRoute,
  PosPosPatientsRoute: PosPosPatientsRoute,
  PosPosIndexRoute: PosPosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface ReceptionistRouteChildren {
  ReceptionistReceptionistBillingRoute: typeof ReceptionistReceptionistBillingRoute
  ReceptionistReceptionistDoctorsRoute: typeof ReceptionistReceptionistDoctorsRoute
  ReceptionistReceptionistPatientsRoute: typeof ReceptionistReceptionistPatientsRoute
  ReceptionistReceptionistPrescriptionsRoute: typeof ReceptionistReceptionistPrescriptionsRoute
  ReceptionistReceptionistProfileRoute: typeof ReceptionistReceptionistProfileRoute
  ReceptionistReceptionistIndexRoute: typeof ReceptionistReceptionistIndexRoute
  ReceptionistReceptionistAppointmentsNewRoute: typeof ReceptionistReceptionistAppointmentsNewRoute
  ReceptionistReceptionistAppointmentsIndexRoute: typeof ReceptionistReceptionistAppointmentsIndexRoute
}

const ReceptionistRouteChildren: ReceptionistRouteChildren = {
  ReceptionistReceptionistBillingRoute: ReceptionistReceptionistBillingRoute,
  ReceptionistReceptionistDoctorsRoute: ReceptionistReceptionistDoctorsRoute,
  ReceptionistReceptionistPatientsRoute: ReceptionistReceptionistPatientsRoute,
  ReceptionistReceptionistPrescriptionsRoute:
    ReceptionistReceptionistPrescriptionsRoute,
  ReceptionistReceptionistProfileRoute: ReceptionistReceptionistProfileRoute,
  ReceptionistReceptionistIndexRoute: ReceptionistReceptionistIndexRoute,
  ReceptionistReceptionistAppointmentsNewRoute:
    ReceptionistReceptionistAppointmentsNewRoute,
  ReceptionistReceptionistAppointmentsIndexRoute:
    ReceptionistReceptionistAppointmentsIndexRoute,
}

const ReceptionistRouteWithChildren = ReceptionistRoute._addFileChildren(
  ReceptionistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeveloperRoute: DeveloperRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  PosRoute: PosRouteWithChildren,
  ReceptionistRoute: ReceptionistRouteWithChildren,
  DisplayRoute: DisplayRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
