/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosRouteImport } from './routes/_pos'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardQueueRouteImport } from './routes/_dashboard/queue'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardPrescriptionsRouteImport } from './routes/_dashboard/prescriptions'
import { Route as DashboardPatientsRouteImport } from './routes/_dashboard/patients'
import { Route as DashboardMedicineCatalogRouteImport } from './routes/_dashboard/medicine-catalog'
import { Route as DashboardDoctorsRouteImport } from './routes/_dashboard/doctors'
import { Route as DashboardDispensingRouteImport } from './routes/_dashboard/dispensing'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard/billing'
import { Route as DashboardAppointmentsRouteImport } from './routes/_dashboard/appointments'
import { Route as PosPosIndexRouteImport } from './routes/_pos/pos/index'
import { Route as DashboardOrganisationIndexRouteImport } from './routes/_dashboard/organisation/index'
import { Route as DashboardDevelopmentIndexRouteImport } from './routes/_dashboard/development/index'
import { Route as PosPosPatientsRouteImport } from './routes/_pos/pos/patients'
import { Route as PosPosBillingRouteImport } from './routes/_pos/pos/billing'
import { Route as PosPosAppointmentsRouteImport } from './routes/_pos/pos/appointments'
import { Route as DashboardOrganisationUsersRouteImport } from './routes/_dashboard/organisation/users'
import { Route as DashboardOrganisationRolesRouteImport } from './routes/_dashboard/organisation/roles'
import { Route as DashboardDevelopmentModulesRouteImport } from './routes/_dashboard/development/modules'
import { Route as DashboardDevelopmentFeaturesRouteImport } from './routes/_dashboard/development/features'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/_pos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsRoute = DashboardPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicineCatalogRoute =
  DashboardMedicineCatalogRouteImport.update({
    id: '/medicine-catalog',
    path: '/medicine-catalog',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDispensingRoute = DashboardDispensingRouteImport.update({
  id: '/dispensing',
  path: '/dispensing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const PosPosIndexRoute = PosPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => PosRoute,
} as any)
const DashboardOrganisationIndexRoute =
  DashboardOrganisationIndexRouteImport.update({
    id: '/organisation/',
    path: '/organisation/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDevelopmentIndexRoute =
  DashboardDevelopmentIndexRouteImport.update({
    id: '/development/',
    path: '/development/',
    getParentRoute: () => DashboardRoute,
  } as any)
const PosPosPatientsRoute = PosPosPatientsRouteImport.update({
  id: '/pos/patients',
  path: '/pos/patients',
  getParentRoute: () => PosRoute,
} as any)
const PosPosBillingRoute = PosPosBillingRouteImport.update({
  id: '/pos/billing',
  path: '/pos/billing',
  getParentRoute: () => PosRoute,
} as any)
const PosPosAppointmentsRoute = PosPosAppointmentsRouteImport.update({
  id: '/pos/appointments',
  path: '/pos/appointments',
  getParentRoute: () => PosRoute,
} as any)
const DashboardOrganisationUsersRoute =
  DashboardOrganisationUsersRouteImport.update({
    id: '/organisation/users',
    path: '/organisation/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganisationRolesRoute =
  DashboardOrganisationRolesRouteImport.update({
    id: '/organisation/roles',
    path: '/organisation/roles',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDevelopmentModulesRoute =
  DashboardDevelopmentModulesRouteImport.update({
    id: '/development/modules',
    path: '/development/modules',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDevelopmentFeaturesRoute =
  DashboardDevelopmentFeaturesRouteImport.update({
    id: '/development/features',
    path: '/development/features',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof DashboardAppointmentsRoute
  '/billing': typeof DashboardBillingRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/dispensing': typeof DashboardDispensingRoute
  '/doctors': typeof DashboardDoctorsRoute
  '/medicine-catalog': typeof DashboardMedicineCatalogRoute
  '/patients': typeof DashboardPatientsRoute
  '/prescriptions': typeof DashboardPrescriptionsRoute
  '/profile': typeof DashboardProfileRoute
  '/queue': typeof DashboardQueueRoute
  '/development/features': typeof DashboardDevelopmentFeaturesRoute
  '/development/modules': typeof DashboardDevelopmentModulesRoute
  '/organisation/roles': typeof DashboardOrganisationRolesRoute
  '/organisation/users': typeof DashboardOrganisationUsersRoute
  '/pos/appointments': typeof PosPosAppointmentsRoute
  '/pos/billing': typeof PosPosBillingRoute
  '/pos/patients': typeof PosPosPatientsRoute
  '/development/': typeof DashboardDevelopmentIndexRoute
  '/organisation/': typeof DashboardOrganisationIndexRoute
  '/pos/': typeof PosPosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof DashboardAppointmentsRoute
  '/billing': typeof DashboardBillingRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/dispensing': typeof DashboardDispensingRoute
  '/doctors': typeof DashboardDoctorsRoute
  '/medicine-catalog': typeof DashboardMedicineCatalogRoute
  '/patients': typeof DashboardPatientsRoute
  '/prescriptions': typeof DashboardPrescriptionsRoute
  '/profile': typeof DashboardProfileRoute
  '/queue': typeof DashboardQueueRoute
  '/development/features': typeof DashboardDevelopmentFeaturesRoute
  '/development/modules': typeof DashboardDevelopmentModulesRoute
  '/organisation/roles': typeof DashboardOrganisationRolesRoute
  '/organisation/users': typeof DashboardOrganisationUsersRoute
  '/pos/appointments': typeof PosPosAppointmentsRoute
  '/pos/billing': typeof PosPosBillingRoute
  '/pos/patients': typeof PosPosPatientsRoute
  '/development': typeof DashboardDevelopmentIndexRoute
  '/organisation': typeof DashboardOrganisationIndexRoute
  '/pos': typeof PosPosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_pos': typeof PosRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/appointments': typeof DashboardAppointmentsRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/dispensing': typeof DashboardDispensingRoute
  '/_dashboard/doctors': typeof DashboardDoctorsRoute
  '/_dashboard/medicine-catalog': typeof DashboardMedicineCatalogRoute
  '/_dashboard/patients': typeof DashboardPatientsRoute
  '/_dashboard/prescriptions': typeof DashboardPrescriptionsRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/queue': typeof DashboardQueueRoute
  '/_dashboard/development/features': typeof DashboardDevelopmentFeaturesRoute
  '/_dashboard/development/modules': typeof DashboardDevelopmentModulesRoute
  '/_dashboard/organisation/roles': typeof DashboardOrganisationRolesRoute
  '/_dashboard/organisation/users': typeof DashboardOrganisationUsersRoute
  '/_pos/pos/appointments': typeof PosPosAppointmentsRoute
  '/_pos/pos/billing': typeof PosPosBillingRoute
  '/_pos/pos/patients': typeof PosPosPatientsRoute
  '/_dashboard/development/': typeof DashboardDevelopmentIndexRoute
  '/_dashboard/organisation/': typeof DashboardOrganisationIndexRoute
  '/_pos/pos/': typeof PosPosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/dispensing'
    | '/doctors'
    | '/medicine-catalog'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/queue'
    | '/development/features'
    | '/development/modules'
    | '/organisation/roles'
    | '/organisation/users'
    | '/pos/appointments'
    | '/pos/billing'
    | '/pos/patients'
    | '/development/'
    | '/organisation/'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/dispensing'
    | '/doctors'
    | '/medicine-catalog'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/queue'
    | '/development/features'
    | '/development/modules'
    | '/organisation/roles'
    | '/organisation/users'
    | '/pos/appointments'
    | '/pos/billing'
    | '/pos/patients'
    | '/development'
    | '/organisation'
    | '/pos'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_pos'
    | '/login'
    | '/_dashboard/appointments'
    | '/_dashboard/billing'
    | '/_dashboard/dashboard'
    | '/_dashboard/dispensing'
    | '/_dashboard/doctors'
    | '/_dashboard/medicine-catalog'
    | '/_dashboard/patients'
    | '/_dashboard/prescriptions'
    | '/_dashboard/profile'
    | '/_dashboard/queue'
    | '/_dashboard/development/features'
    | '/_dashboard/development/modules'
    | '/_dashboard/organisation/roles'
    | '/_dashboard/organisation/users'
    | '/_pos/pos/appointments'
    | '/_pos/pos/billing'
    | '/_pos/pos/patients'
    | '/_dashboard/development/'
    | '/_dashboard/organisation/'
    | '/_pos/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PosRoute: typeof PosRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos': {
      id: '/_pos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/queue': {
      id: '/_dashboard/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/prescriptions': {
      id: '/_dashboard/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/patients': {
      id: '/_dashboard/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/medicine-catalog': {
      id: '/_dashboard/medicine-catalog'
      path: '/medicine-catalog'
      fullPath: '/medicine-catalog'
      preLoaderRoute: typeof DashboardMedicineCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/doctors': {
      id: '/_dashboard/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dispensing': {
      id: '/_dashboard/dispensing'
      path: '/dispensing'
      fullPath: '/dispensing'
      preLoaderRoute: typeof DashboardDispensingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments': {
      id: '/_dashboard/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_pos/pos/': {
      id: '/_pos/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosPosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/_dashboard/organisation/': {
      id: '/_dashboard/organisation/'
      path: '/organisation'
      fullPath: '/organisation/'
      preLoaderRoute: typeof DashboardOrganisationIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/development/': {
      id: '/_dashboard/development/'
      path: '/development'
      fullPath: '/development/'
      preLoaderRoute: typeof DashboardDevelopmentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_pos/pos/patients': {
      id: '/_pos/pos/patients'
      path: '/pos/patients'
      fullPath: '/pos/patients'
      preLoaderRoute: typeof PosPosPatientsRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/pos/billing': {
      id: '/_pos/pos/billing'
      path: '/pos/billing'
      fullPath: '/pos/billing'
      preLoaderRoute: typeof PosPosBillingRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/pos/appointments': {
      id: '/_pos/pos/appointments'
      path: '/pos/appointments'
      fullPath: '/pos/appointments'
      preLoaderRoute: typeof PosPosAppointmentsRouteImport
      parentRoute: typeof PosRoute
    }
    '/_dashboard/organisation/users': {
      id: '/_dashboard/organisation/users'
      path: '/organisation/users'
      fullPath: '/organisation/users'
      preLoaderRoute: typeof DashboardOrganisationUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organisation/roles': {
      id: '/_dashboard/organisation/roles'
      path: '/organisation/roles'
      fullPath: '/organisation/roles'
      preLoaderRoute: typeof DashboardOrganisationRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/development/modules': {
      id: '/_dashboard/development/modules'
      path: '/development/modules'
      fullPath: '/development/modules'
      preLoaderRoute: typeof DashboardDevelopmentModulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/development/features': {
      id: '/_dashboard/development/features'
      path: '/development/features'
      fullPath: '/development/features'
      preLoaderRoute: typeof DashboardDevelopmentFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDispensingRoute: typeof DashboardDispensingRoute
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardMedicineCatalogRoute: typeof DashboardMedicineCatalogRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardPrescriptionsRoute: typeof DashboardPrescriptionsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardDevelopmentFeaturesRoute: typeof DashboardDevelopmentFeaturesRoute
  DashboardDevelopmentModulesRoute: typeof DashboardDevelopmentModulesRoute
  DashboardOrganisationRolesRoute: typeof DashboardOrganisationRolesRoute
  DashboardOrganisationUsersRoute: typeof DashboardOrganisationUsersRoute
  DashboardDevelopmentIndexRoute: typeof DashboardDevelopmentIndexRoute
  DashboardOrganisationIndexRoute: typeof DashboardOrganisationIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDispensingRoute: DashboardDispensingRoute,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardMedicineCatalogRoute: DashboardMedicineCatalogRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardPrescriptionsRoute: DashboardPrescriptionsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardDevelopmentFeaturesRoute: DashboardDevelopmentFeaturesRoute,
  DashboardDevelopmentModulesRoute: DashboardDevelopmentModulesRoute,
  DashboardOrganisationRolesRoute: DashboardOrganisationRolesRoute,
  DashboardOrganisationUsersRoute: DashboardOrganisationUsersRoute,
  DashboardDevelopmentIndexRoute: DashboardDevelopmentIndexRoute,
  DashboardOrganisationIndexRoute: DashboardOrganisationIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PosRouteChildren {
  PosPosAppointmentsRoute: typeof PosPosAppointmentsRoute
  PosPosBillingRoute: typeof PosPosBillingRoute
  PosPosPatientsRoute: typeof PosPosPatientsRoute
  PosPosIndexRoute: typeof PosPosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosPosAppointmentsRoute: PosPosAppointmentsRoute,
  PosPosBillingRoute: PosPosBillingRoute,
  PosPosPatientsRoute: PosPosPatientsRoute,
  PosPosIndexRoute: PosPosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PosRoute: PosRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
