/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminOrganisationCountriesIndexRouteImport } from './routes/_admin/organisation/countries/index'
import { Route as AdminOrganisationCountriesNewRouteImport } from './routes/_admin/organisation/countries/new'
import { Route as AdminOrganisationCustomersIndexRouteImport } from './routes/_admin/organisation/customers/index'
import { Route as AdminOrganisationCustomersNewRouteImport } from './routes/_admin/organisation/customers/new'
import { Route as AdminOrganisationDepartmentsIndexRouteImport } from './routes/_admin/organisation/departments/index'
import { Route as AdminOrganisationDepartmentsNewRouteImport } from './routes/_admin/organisation/departments/new'
import { Route as AdminOrganisationDesignationsIndexRouteImport } from './routes/_admin/organisation/designations/index'
import { Route as AdminOrganisationDesignationsNewRouteImport } from './routes/_admin/organisation/designations/new'
import { Route as AdminOrganisationEmployeesIndexRouteImport } from './routes/_admin/organisation/employees/index'
import { Route as AdminOrganisationEmployeesNewRouteImport } from './routes/_admin/organisation/employees/new'
import { Route as AdminOrganisationLicensesIndexRouteImport } from './routes/_admin/organisation/licenses/index'
import { Route as AdminOrganisationLicensesNewRouteImport } from './routes/_admin/organisation/licenses/new'
import { Route as AdminOrganisationOrganizationsIndexRouteImport } from './routes/_admin/organisation/organizations/index'
import { Route as AdminOrganisationOrganizationsNewRouteImport } from './routes/_admin/organisation/organizations/new'
import { Route as AdminOrganisationStatesIndexRouteImport } from './routes/_admin/organisation/states/index'
import { Route as AdminOrganisationStatesNewRouteImport } from './routes/_admin/organisation/states/new'
import { Route as AdminOrganisationCountriesCountryIdEditRouteImport } from './routes/_admin/organisation/countries/$countryId.edit'
import { Route as AdminOrganisationCustomersCustomerIdEditRouteImport } from './routes/_admin/organisation/customers/$customerId.edit'
import { Route as AdminOrganisationDepartmentsDepartmentIdEditRouteImport } from './routes/_admin/organisation/departments/$departmentId.edit'
import { Route as AdminOrganisationDesignationsDesignationIdEditRouteImport } from './routes/_admin/organisation/designations/$designationId.edit'
import { Route as AdminOrganisationEmployeesEmployeeIdEditRouteImport } from './routes/_admin/organisation/employees/$employeeId.edit'
import { Route as AdminOrganisationLicensesLicenseIdEditRouteImport } from './routes/_admin/organisation/licenses/$licenseId.edit'
import { Route as AdminOrganisationOrganizationsOrganizationIdEditRouteImport } from './routes/_admin/organisation/organizations/$organizationId.edit'
import { Route as AdminOrganisationStatesStateIdEditRouteImport } from './routes/_admin/organisation/states/$stateId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganisationCountriesIndexRoute =
  AdminOrganisationCountriesIndexRouteImport.update({
    id: '/organisation/countries/',
    path: '/organisation/countries/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationCountriesNewRoute =
  AdminOrganisationCountriesNewRouteImport.update({
    id: '/organisation/countries/new',
    path: '/organisation/countries/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationCustomersIndexRoute =
  AdminOrganisationCustomersIndexRouteImport.update({
    id: '/organisation/customers/',
    path: '/organisation/customers/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationCustomersNewRoute =
  AdminOrganisationCustomersNewRouteImport.update({
    id: '/organisation/customers/new',
    path: '/organisation/customers/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationDepartmentsIndexRoute =
  AdminOrganisationDepartmentsIndexRouteImport.update({
    id: '/organisation/departments/',
    path: '/organisation/departments/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationDepartmentsNewRoute =
  AdminOrganisationDepartmentsNewRouteImport.update({
    id: '/organisation/departments/new',
    path: '/organisation/departments/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationDesignationsIndexRoute =
  AdminOrganisationDesignationsIndexRouteImport.update({
    id: '/organisation/designations/',
    path: '/organisation/designations/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationDesignationsNewRoute =
  AdminOrganisationDesignationsNewRouteImport.update({
    id: '/organisation/designations/new',
    path: '/organisation/designations/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationEmployeesIndexRoute =
  AdminOrganisationEmployeesIndexRouteImport.update({
    id: '/organisation/employees/',
    path: '/organisation/employees/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationEmployeesNewRoute =
  AdminOrganisationEmployeesNewRouteImport.update({
    id: '/organisation/employees/new',
    path: '/organisation/employees/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationLicensesIndexRoute =
  AdminOrganisationLicensesIndexRouteImport.update({
    id: '/organisation/licenses/',
    path: '/organisation/licenses/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationLicensesNewRoute =
  AdminOrganisationLicensesNewRouteImport.update({
    id: '/organisation/licenses/new',
    path: '/organisation/licenses/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationOrganizationsIndexRoute =
  AdminOrganisationOrganizationsIndexRouteImport.update({
    id: '/organisation/organizations/',
    path: '/organisation/organizations/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationOrganizationsNewRoute =
  AdminOrganisationOrganizationsNewRouteImport.update({
    id: '/organisation/organizations/new',
    path: '/organisation/organizations/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationStatesIndexRoute =
  AdminOrganisationStatesIndexRouteImport.update({
    id: '/organisation/states/',
    path: '/organisation/states/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationStatesNewRoute =
  AdminOrganisationStatesNewRouteImport.update({
    id: '/organisation/states/new',
    path: '/organisation/states/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationCountriesCountryIdEditRoute =
  AdminOrganisationCountriesCountryIdEditRouteImport.update({
    id: '/organisation/countries/$countryId/edit',
    path: '/organisation/countries/$countryId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationCustomersCustomerIdEditRoute =
  AdminOrganisationCustomersCustomerIdEditRouteImport.update({
    id: '/organisation/customers/$customerId/edit',
    path: '/organisation/customers/$customerId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationDepartmentsDepartmentIdEditRoute =
  AdminOrganisationDepartmentsDepartmentIdEditRouteImport.update({
    id: '/organisation/departments/$departmentId/edit',
    path: '/organisation/departments/$departmentId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationDesignationsDesignationIdEditRoute =
  AdminOrganisationDesignationsDesignationIdEditRouteImport.update({
    id: '/organisation/designations/$designationId/edit',
    path: '/organisation/designations/$designationId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationEmployeesEmployeeIdEditRoute =
  AdminOrganisationEmployeesEmployeeIdEditRouteImport.update({
    id: '/organisation/employees/$employeeId/edit',
    path: '/organisation/employees/$employeeId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationLicensesLicenseIdEditRoute =
  AdminOrganisationLicensesLicenseIdEditRouteImport.update({
    id: '/organisation/licenses/$licenseId/edit',
    path: '/organisation/licenses/$licenseId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationOrganizationsOrganizationIdEditRoute =
  AdminOrganisationOrganizationsOrganizationIdEditRouteImport.update({
    id: '/organisation/organizations/$organizationId/edit',
    path: '/organisation/organizations/$organizationId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganisationStatesStateIdEditRoute =
  AdminOrganisationStatesStateIdEditRouteImport.update({
    id: '/organisation/states/$stateId/edit',
    path: '/organisation/states/$stateId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/users': typeof AdminUsersRoute
  '/organisation/countries/new': typeof AdminOrganisationCountriesNewRoute
  '/organisation/customers/new': typeof AdminOrganisationCustomersNewRoute
  '/organisation/departments/new': typeof AdminOrganisationDepartmentsNewRoute
  '/organisation/designations/new': typeof AdminOrganisationDesignationsNewRoute
  '/organisation/employees/new': typeof AdminOrganisationEmployeesNewRoute
  '/organisation/licenses/new': typeof AdminOrganisationLicensesNewRoute
  '/organisation/organizations/new': typeof AdminOrganisationOrganizationsNewRoute
  '/organisation/states/new': typeof AdminOrganisationStatesNewRoute
  '/organisation/countries/': typeof AdminOrganisationCountriesIndexRoute
  '/organisation/customers/': typeof AdminOrganisationCustomersIndexRoute
  '/organisation/departments/': typeof AdminOrganisationDepartmentsIndexRoute
  '/organisation/designations/': typeof AdminOrganisationDesignationsIndexRoute
  '/organisation/employees/': typeof AdminOrganisationEmployeesIndexRoute
  '/organisation/licenses/': typeof AdminOrganisationLicensesIndexRoute
  '/organisation/organizations/': typeof AdminOrganisationOrganizationsIndexRoute
  '/organisation/states/': typeof AdminOrganisationStatesIndexRoute
  '/organisation/countries/$countryId/edit': typeof AdminOrganisationCountriesCountryIdEditRoute
  '/organisation/customers/$customerId/edit': typeof AdminOrganisationCustomersCustomerIdEditRoute
  '/organisation/departments/$departmentId/edit': typeof AdminOrganisationDepartmentsDepartmentIdEditRoute
  '/organisation/designations/$designationId/edit': typeof AdminOrganisationDesignationsDesignationIdEditRoute
  '/organisation/employees/$employeeId/edit': typeof AdminOrganisationEmployeesEmployeeIdEditRoute
  '/organisation/licenses/$licenseId/edit': typeof AdminOrganisationLicensesLicenseIdEditRoute
  '/organisation/organizations/$organizationId/edit': typeof AdminOrganisationOrganizationsOrganizationIdEditRoute
  '/organisation/states/$stateId/edit': typeof AdminOrganisationStatesStateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/users': typeof AdminUsersRoute
  '/organisation/countries/new': typeof AdminOrganisationCountriesNewRoute
  '/organisation/customers/new': typeof AdminOrganisationCustomersNewRoute
  '/organisation/departments/new': typeof AdminOrganisationDepartmentsNewRoute
  '/organisation/designations/new': typeof AdminOrganisationDesignationsNewRoute
  '/organisation/employees/new': typeof AdminOrganisationEmployeesNewRoute
  '/organisation/licenses/new': typeof AdminOrganisationLicensesNewRoute
  '/organisation/organizations/new': typeof AdminOrganisationOrganizationsNewRoute
  '/organisation/states/new': typeof AdminOrganisationStatesNewRoute
  '/organisation/countries': typeof AdminOrganisationCountriesIndexRoute
  '/organisation/customers': typeof AdminOrganisationCustomersIndexRoute
  '/organisation/departments': typeof AdminOrganisationDepartmentsIndexRoute
  '/organisation/designations': typeof AdminOrganisationDesignationsIndexRoute
  '/organisation/employees': typeof AdminOrganisationEmployeesIndexRoute
  '/organisation/licenses': typeof AdminOrganisationLicensesIndexRoute
  '/organisation/organizations': typeof AdminOrganisationOrganizationsIndexRoute
  '/organisation/states': typeof AdminOrganisationStatesIndexRoute
  '/organisation/countries/$countryId/edit': typeof AdminOrganisationCountriesCountryIdEditRoute
  '/organisation/customers/$customerId/edit': typeof AdminOrganisationCustomersCustomerIdEditRoute
  '/organisation/departments/$departmentId/edit': typeof AdminOrganisationDepartmentsDepartmentIdEditRoute
  '/organisation/designations/$designationId/edit': typeof AdminOrganisationDesignationsDesignationIdEditRoute
  '/organisation/employees/$employeeId/edit': typeof AdminOrganisationEmployeesEmployeeIdEditRoute
  '/organisation/licenses/$licenseId/edit': typeof AdminOrganisationLicensesLicenseIdEditRoute
  '/organisation/organizations/$organizationId/edit': typeof AdminOrganisationOrganizationsOrganizationIdEditRoute
  '/organisation/states/$stateId/edit': typeof AdminOrganisationStatesStateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/organisation/countries/new': typeof AdminOrganisationCountriesNewRoute
  '/_admin/organisation/customers/new': typeof AdminOrganisationCustomersNewRoute
  '/_admin/organisation/departments/new': typeof AdminOrganisationDepartmentsNewRoute
  '/_admin/organisation/designations/new': typeof AdminOrganisationDesignationsNewRoute
  '/_admin/organisation/employees/new': typeof AdminOrganisationEmployeesNewRoute
  '/_admin/organisation/licenses/new': typeof AdminOrganisationLicensesNewRoute
  '/_admin/organisation/organizations/new': typeof AdminOrganisationOrganizationsNewRoute
  '/_admin/organisation/states/new': typeof AdminOrganisationStatesNewRoute
  '/_admin/organisation/countries/': typeof AdminOrganisationCountriesIndexRoute
  '/_admin/organisation/customers/': typeof AdminOrganisationCustomersIndexRoute
  '/_admin/organisation/departments/': typeof AdminOrganisationDepartmentsIndexRoute
  '/_admin/organisation/designations/': typeof AdminOrganisationDesignationsIndexRoute
  '/_admin/organisation/employees/': typeof AdminOrganisationEmployeesIndexRoute
  '/_admin/organisation/licenses/': typeof AdminOrganisationLicensesIndexRoute
  '/_admin/organisation/organizations/': typeof AdminOrganisationOrganizationsIndexRoute
  '/_admin/organisation/states/': typeof AdminOrganisationStatesIndexRoute
  '/_admin/organisation/countries/$countryId/edit': typeof AdminOrganisationCountriesCountryIdEditRoute
  '/_admin/organisation/customers/$customerId/edit': typeof AdminOrganisationCustomersCustomerIdEditRoute
  '/_admin/organisation/departments/$departmentId/edit': typeof AdminOrganisationDepartmentsDepartmentIdEditRoute
  '/_admin/organisation/designations/$designationId/edit': typeof AdminOrganisationDesignationsDesignationIdEditRoute
  '/_admin/organisation/employees/$employeeId/edit': typeof AdminOrganisationEmployeesEmployeeIdEditRoute
  '/_admin/organisation/licenses/$licenseId/edit': typeof AdminOrganisationLicensesLicenseIdEditRoute
  '/_admin/organisation/organizations/$organizationId/edit': typeof AdminOrganisationOrganizationsOrganizationIdEditRoute
  '/_admin/organisation/states/$stateId/edit': typeof AdminOrganisationStatesStateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/users'
    | '/organisation/countries/new'
    | '/organisation/customers/new'
    | '/organisation/departments/new'
    | '/organisation/designations/new'
    | '/organisation/employees/new'
    | '/organisation/licenses/new'
    | '/organisation/organizations/new'
    | '/organisation/states/new'
    | '/organisation/countries/'
    | '/organisation/customers/'
    | '/organisation/departments/'
    | '/organisation/designations/'
    | '/organisation/employees/'
    | '/organisation/licenses/'
    | '/organisation/organizations/'
    | '/organisation/states/'
    | '/organisation/countries/$countryId/edit'
    | '/organisation/customers/$customerId/edit'
    | '/organisation/departments/$departmentId/edit'
    | '/organisation/designations/$designationId/edit'
    | '/organisation/employees/$employeeId/edit'
    | '/organisation/licenses/$licenseId/edit'
    | '/organisation/organizations/$organizationId/edit'
    | '/organisation/states/$stateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/users'
    | '/organisation/countries/new'
    | '/organisation/customers/new'
    | '/organisation/departments/new'
    | '/organisation/designations/new'
    | '/organisation/employees/new'
    | '/organisation/licenses/new'
    | '/organisation/organizations/new'
    | '/organisation/states/new'
    | '/organisation/countries'
    | '/organisation/customers'
    | '/organisation/departments'
    | '/organisation/designations'
    | '/organisation/employees'
    | '/organisation/licenses'
    | '/organisation/organizations'
    | '/organisation/states'
    | '/organisation/countries/$countryId/edit'
    | '/organisation/customers/$customerId/edit'
    | '/organisation/departments/$departmentId/edit'
    | '/organisation/designations/$designationId/edit'
    | '/organisation/employees/$employeeId/edit'
    | '/organisation/licenses/$licenseId/edit'
    | '/organisation/organizations/$organizationId/edit'
    | '/organisation/states/$stateId/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/dashboard'
    | '/_admin/users'
    | '/_admin/organisation/countries/new'
    | '/_admin/organisation/customers/new'
    | '/_admin/organisation/departments/new'
    | '/_admin/organisation/designations/new'
    | '/_admin/organisation/employees/new'
    | '/_admin/organisation/licenses/new'
    | '/_admin/organisation/organizations/new'
    | '/_admin/organisation/states/new'
    | '/_admin/organisation/countries/'
    | '/_admin/organisation/customers/'
    | '/_admin/organisation/departments/'
    | '/_admin/organisation/designations/'
    | '/_admin/organisation/employees/'
    | '/_admin/organisation/licenses/'
    | '/_admin/organisation/organizations/'
    | '/_admin/organisation/states/'
    | '/_admin/organisation/countries/$countryId/edit'
    | '/_admin/organisation/customers/$customerId/edit'
    | '/_admin/organisation/departments/$departmentId/edit'
    | '/_admin/organisation/designations/$designationId/edit'
    | '/_admin/organisation/employees/$employeeId/edit'
    | '/_admin/organisation/licenses/$licenseId/edit'
    | '/_admin/organisation/organizations/$organizationId/edit'
    | '/_admin/organisation/states/$stateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/countries/': {
      id: '/_admin/organisation/countries/'
      path: '/organisation/countries'
      fullPath: '/organisation/countries/'
      preLoaderRoute: typeof AdminOrganisationCountriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/countries/new': {
      id: '/_admin/organisation/countries/new'
      path: '/organisation/countries/new'
      fullPath: '/organisation/countries/new'
      preLoaderRoute: typeof AdminOrganisationCountriesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/customers/': {
      id: '/_admin/organisation/customers/'
      path: '/organisation/customers'
      fullPath: '/organisation/customers/'
      preLoaderRoute: typeof AdminOrganisationCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/customers/new': {
      id: '/_admin/organisation/customers/new'
      path: '/organisation/customers/new'
      fullPath: '/organisation/customers/new'
      preLoaderRoute: typeof AdminOrganisationCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/departments/': {
      id: '/_admin/organisation/departments/'
      path: '/organisation/departments'
      fullPath: '/organisation/departments/'
      preLoaderRoute: typeof AdminOrganisationDepartmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/departments/new': {
      id: '/_admin/organisation/departments/new'
      path: '/organisation/departments/new'
      fullPath: '/organisation/departments/new'
      preLoaderRoute: typeof AdminOrganisationDepartmentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/designations/': {
      id: '/_admin/organisation/designations/'
      path: '/organisation/designations'
      fullPath: '/organisation/designations/'
      preLoaderRoute: typeof AdminOrganisationDesignationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/designations/new': {
      id: '/_admin/organisation/designations/new'
      path: '/organisation/designations/new'
      fullPath: '/organisation/designations/new'
      preLoaderRoute: typeof AdminOrganisationDesignationsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/employees/': {
      id: '/_admin/organisation/employees/'
      path: '/organisation/employees'
      fullPath: '/organisation/employees/'
      preLoaderRoute: typeof AdminOrganisationEmployeesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/employees/new': {
      id: '/_admin/organisation/employees/new'
      path: '/organisation/employees/new'
      fullPath: '/organisation/employees/new'
      preLoaderRoute: typeof AdminOrganisationEmployeesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/licenses/': {
      id: '/_admin/organisation/licenses/'
      path: '/organisation/licenses'
      fullPath: '/organisation/licenses/'
      preLoaderRoute: typeof AdminOrganisationLicensesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/licenses/new': {
      id: '/_admin/organisation/licenses/new'
      path: '/organisation/licenses/new'
      fullPath: '/organisation/licenses/new'
      preLoaderRoute: typeof AdminOrganisationLicensesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/organizations/': {
      id: '/_admin/organisation/organizations/'
      path: '/organisation/organizations'
      fullPath: '/organisation/organizations/'
      preLoaderRoute: typeof AdminOrganisationOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/organizations/new': {
      id: '/_admin/organisation/organizations/new'
      path: '/organisation/organizations/new'
      fullPath: '/organisation/organizations/new'
      preLoaderRoute: typeof AdminOrganisationOrganizationsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/states/': {
      id: '/_admin/organisation/states/'
      path: '/organisation/states'
      fullPath: '/organisation/states/'
      preLoaderRoute: typeof AdminOrganisationStatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/states/new': {
      id: '/_admin/organisation/states/new'
      path: '/organisation/states/new'
      fullPath: '/organisation/states/new'
      preLoaderRoute: typeof AdminOrganisationStatesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/countries/$countryId/edit': {
      id: '/_admin/organisation/countries/$countryId/edit'
      path: '/organisation/countries/$countryId/edit'
      fullPath: '/organisation/countries/$countryId/edit'
      preLoaderRoute: typeof AdminOrganisationCountriesCountryIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/customers/$customerId/edit': {
      id: '/_admin/organisation/customers/$customerId/edit'
      path: '/organisation/customers/$customerId/edit'
      fullPath: '/organisation/customers/$customerId/edit'
      preLoaderRoute: typeof AdminOrganisationCustomersCustomerIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/departments/$departmentId/edit': {
      id: '/_admin/organisation/departments/$departmentId/edit'
      path: '/organisation/departments/$departmentId/edit'
      fullPath: '/organisation/departments/$departmentId/edit'
      preLoaderRoute: typeof AdminOrganisationDepartmentsDepartmentIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/designations/$designationId/edit': {
      id: '/_admin/organisation/designations/$designationId/edit'
      path: '/organisation/designations/$designationId/edit'
      fullPath: '/organisation/designations/$designationId/edit'
      preLoaderRoute: typeof AdminOrganisationDesignationsDesignationIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/employees/$employeeId/edit': {
      id: '/_admin/organisation/employees/$employeeId/edit'
      path: '/organisation/employees/$employeeId/edit'
      fullPath: '/organisation/employees/$employeeId/edit'
      preLoaderRoute: typeof AdminOrganisationEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/licenses/$licenseId/edit': {
      id: '/_admin/organisation/licenses/$licenseId/edit'
      path: '/organisation/licenses/$licenseId/edit'
      fullPath: '/organisation/licenses/$licenseId/edit'
      preLoaderRoute: typeof AdminOrganisationLicensesLicenseIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/organizations/$organizationId/edit': {
      id: '/_admin/organisation/organizations/$organizationId/edit'
      path: '/organisation/organizations/$organizationId/edit'
      fullPath: '/organisation/organizations/$organizationId/edit'
      preLoaderRoute: typeof AdminOrganisationOrganizationsOrganizationIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organisation/states/$stateId/edit': {
      id: '/_admin/organisation/states/$stateId/edit'
      path: '/organisation/states/$stateId/edit'
      fullPath: '/organisation/states/$stateId/edit'
      preLoaderRoute: typeof AdminOrganisationStatesStateIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminOrganisationCountriesNewRoute: typeof AdminOrganisationCountriesNewRoute
  AdminOrganisationCustomersNewRoute: typeof AdminOrganisationCustomersNewRoute
  AdminOrganisationDepartmentsNewRoute: typeof AdminOrganisationDepartmentsNewRoute
  AdminOrganisationDesignationsNewRoute: typeof AdminOrganisationDesignationsNewRoute
  AdminOrganisationEmployeesNewRoute: typeof AdminOrganisationEmployeesNewRoute
  AdminOrganisationLicensesNewRoute: typeof AdminOrganisationLicensesNewRoute
  AdminOrganisationOrganizationsNewRoute: typeof AdminOrganisationOrganizationsNewRoute
  AdminOrganisationStatesNewRoute: typeof AdminOrganisationStatesNewRoute
  AdminOrganisationCountriesIndexRoute: typeof AdminOrganisationCountriesIndexRoute
  AdminOrganisationCustomersIndexRoute: typeof AdminOrganisationCustomersIndexRoute
  AdminOrganisationDepartmentsIndexRoute: typeof AdminOrganisationDepartmentsIndexRoute
  AdminOrganisationDesignationsIndexRoute: typeof AdminOrganisationDesignationsIndexRoute
  AdminOrganisationEmployeesIndexRoute: typeof AdminOrganisationEmployeesIndexRoute
  AdminOrganisationLicensesIndexRoute: typeof AdminOrganisationLicensesIndexRoute
  AdminOrganisationOrganizationsIndexRoute: typeof AdminOrganisationOrganizationsIndexRoute
  AdminOrganisationStatesIndexRoute: typeof AdminOrganisationStatesIndexRoute
  AdminOrganisationCountriesCountryIdEditRoute: typeof AdminOrganisationCountriesCountryIdEditRoute
  AdminOrganisationCustomersCustomerIdEditRoute: typeof AdminOrganisationCustomersCustomerIdEditRoute
  AdminOrganisationDepartmentsDepartmentIdEditRoute: typeof AdminOrganisationDepartmentsDepartmentIdEditRoute
  AdminOrganisationDesignationsDesignationIdEditRoute: typeof AdminOrganisationDesignationsDesignationIdEditRoute
  AdminOrganisationEmployeesEmployeeIdEditRoute: typeof AdminOrganisationEmployeesEmployeeIdEditRoute
  AdminOrganisationLicensesLicenseIdEditRoute: typeof AdminOrganisationLicensesLicenseIdEditRoute
  AdminOrganisationOrganizationsOrganizationIdEditRoute: typeof AdminOrganisationOrganizationsOrganizationIdEditRoute
  AdminOrganisationStatesStateIdEditRoute: typeof AdminOrganisationStatesStateIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminOrganisationCountriesNewRoute: AdminOrganisationCountriesNewRoute,
  AdminOrganisationCustomersNewRoute: AdminOrganisationCustomersNewRoute,
  AdminOrganisationDepartmentsNewRoute: AdminOrganisationDepartmentsNewRoute,
  AdminOrganisationDesignationsNewRoute: AdminOrganisationDesignationsNewRoute,
  AdminOrganisationEmployeesNewRoute: AdminOrganisationEmployeesNewRoute,
  AdminOrganisationLicensesNewRoute: AdminOrganisationLicensesNewRoute,
  AdminOrganisationOrganizationsNewRoute:
    AdminOrganisationOrganizationsNewRoute,
  AdminOrganisationStatesNewRoute: AdminOrganisationStatesNewRoute,
  AdminOrganisationCountriesIndexRoute: AdminOrganisationCountriesIndexRoute,
  AdminOrganisationCustomersIndexRoute: AdminOrganisationCustomersIndexRoute,
  AdminOrganisationDepartmentsIndexRoute:
    AdminOrganisationDepartmentsIndexRoute,
  AdminOrganisationDesignationsIndexRoute:
    AdminOrganisationDesignationsIndexRoute,
  AdminOrganisationEmployeesIndexRoute: AdminOrganisationEmployeesIndexRoute,
  AdminOrganisationLicensesIndexRoute: AdminOrganisationLicensesIndexRoute,
  AdminOrganisationOrganizationsIndexRoute:
    AdminOrganisationOrganizationsIndexRoute,
  AdminOrganisationStatesIndexRoute: AdminOrganisationStatesIndexRoute,
  AdminOrganisationCountriesCountryIdEditRoute:
    AdminOrganisationCountriesCountryIdEditRoute,
  AdminOrganisationCustomersCustomerIdEditRoute:
    AdminOrganisationCustomersCustomerIdEditRoute,
  AdminOrganisationDepartmentsDepartmentIdEditRoute:
    AdminOrganisationDepartmentsDepartmentIdEditRoute,
  AdminOrganisationDesignationsDesignationIdEditRoute:
    AdminOrganisationDesignationsDesignationIdEditRoute,
  AdminOrganisationEmployeesEmployeeIdEditRoute:
    AdminOrganisationEmployeesEmployeeIdEditRoute,
  AdminOrganisationLicensesLicenseIdEditRoute:
    AdminOrganisationLicensesLicenseIdEditRoute,
  AdminOrganisationOrganizationsOrganizationIdEditRoute:
    AdminOrganisationOrganizationsOrganizationIdEditRoute,
  AdminOrganisationStatesStateIdEditRoute:
    AdminOrganisationStatesStateIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
